name: Build deb

on:
  workflow_dispatch:
  push:
  paths:
      - 'CMakeLists.txt'

jobs:
  check_update:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Check latest version
        uses: actions/checkout@v4

      - name: Install dep
        run: |
          sudo apt update&&sudo apt install -y git wget debhelper dpkg-dev ninja-build
          yes | sudo apt install --no-install-recommends -y curl xz-utils \
          cmake \
          clang-tidy \
          libseccomp-dev \
          libcap-dev \
          libc6-dev \
          binutils uidmap
      - name: Configure
        run: cmake . -Gninja -DENABLE_DEBUG=on -DBUILD_LIB=on
      - name: Build
        run: ninja
