name: Build release

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    name: Check update
    runs-on: ubuntu-latest
    steps:
      - name: Check latest version
        id: check_version
        uses: actions/checkout@v4
      - run: |
          sudo apt update&&sudo apt install -y git wget
          yes | sudo apt install --no-install-recommends -y curl xz-utils \
          make \
          clang \
          libseccomp-dev \
          libcap-dev \
          libc6-dev \
          binutils ninja-build uidmap
      - name: configure
        run: ./configure --enable-debug --enable-static
      - name: build
        run: make
      - name: run cmake
        run: cmake . -GNinja -DCMAKE_C_COMPILER=$(which gcc)
      - name: build
        run: ninja
      - name: clean
        run: git clean -dxf
