name: Build deb

on:
  workflow_dispatch:
  push:
    paths:
      - 'debian/**'
      - '.github/workflows/deb.yml'
      - 'arm64.sh'
      - 'Makefile.am'

jobs:
  amd64:
    name: Build amd64 deb
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - name: Test
        run: |
          apt update && apt install -y git wget debhelper dpkg-dev dh-make dh-exec dh-autoreconf

      - name: Check latest version
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global --add safe.directory /__w/ruri/ruri
          rm -rf -v build src/include/version.h
          bash -x autogen.sh
          git config --global user.name "root"
          git config --global user.email "your_email@example.com"
          git add .
          git commit -m "Test"

      - name: build amd64 deb
        run: |
          git archive --prefix=ruri-3.8/ -o ../ruri_3.8.orig.tar.gz HEAD
          apt build-dep . -y
          dpkg-buildpackage -F -d
          mkdir -p build
          mv ../ruri_* build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ruri-deb-amd64
          path: build/ruri*

  arm64:
    name: Build arm64 deb
    runs-on: ubuntu-24.04-arm
    container: debian:bookworm
    steps:
      - name: Test
        run: |
          apt update && apt install -y git wget debhelper dpkg-dev dh-make dh-exec dh-autoreconf

      - name: Check latest version
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global --add safe.directory /__w/ruri/ruri
          rm -rf -v build  src/include/version.h
          bash -x autogen.sh
          git config --global user.name "root"
          git config --global user.email "your_email@example.com"
          git add .
          git commit -m "Test"

      - name: build arm64 deb
        run: |
          git archive --prefix=ruri-3.8/ -o ../ruri_3.8.orig.tar.gz HEAD
          apt build-dep . -y
          dpkg-buildpackage -b -us -uc -d
          mkdir -p build
          mv ../ruri_* build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ruri-deb-arm64
          path: build/ruri*

  release:
    name: Release
    needs:
      - amd64
      - arm64
    runs-on: ubuntu-latest
    steps:
      - name: Check latest version
        uses: actions/download-artifact@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: rurideb-${{ github.sha }}
          name: rurideb-${{ github.sha }}
          prerelease: false
          files: |
             ruri-deb-arm64/*
             ruri-deb-amd64/*
